---
version: "2"

run:
  timeout: 10m
  tests: true

linters:
  enable:
    # Default enabled linters (essential)
    - errcheck # check unchecked errors
    - govet # official vet checks + suspicious code
    - ineffassign # detects useless assignments
    - staticcheck # powerful bug & style checker
    - unused # unused vars, funcs, consts

    # Code quality & style
    - revive # configurable linter for style & readability
    - gocritic # bug, performance, style improvements
    - godot # check that comments are sentences
    - whitespace # whitespace issues
    - misspell # spelling mistakes

    # Security & reliability
    - gosec # security checks
    - bodyclose # HTTP response body closes
    - rowserrcheck # SQL rows.Err() checks
    - sqlclosecheck # SQL close checks
    - nilerr # nil error returns
    - errorlint # error wrapping issues
    - contextcheck # context usage
    - noctx # find sending context.Background() or context.TODO()
    - makezero # finds slice declarations with non-zero length and zero capacity

    # Complexity & maintainability
    - gocyclo # cyclomatic complexity
    - funlen # function length
    - nestif # deeply nested if statements
    - gocognit # cognitive complexity

    # Performance
    - prealloc # slice preallocation
    - unconvert # unnecessary conversions
    - copyloopvar # loop variable capture (Go 1.22+)
    - wastedassign # finds wasted assignments
    - usestdlibvars # finds where standard library variables can be used

    # Error handling & types
    - err113 # error handling checks
    - forcetypeassert # forced type assertions
    - ireturn # interface return types
    - exhaustive # enum exhaustiveness

    # Testing
    - testifylint # usage of testify in tests
    - paralleltest # missing t.Parallel()
    - thelper # test helpers

    # Code duplication & naming
    - dupl # duplicate code
    - unparam # unused parameters
    - nakedret # naked returns
    - nolintlint # nolint directive usage
    - predeclared # shadowing predeclared identifiers

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true

    staticcheck:
      checks: ["all"]

    gosec:
      severity: medium
      confidence: medium

    funlen:
      lines: 120
      statements: 60

    gocyclo:
      min-complexity: 20

    gocognit:
      min-complexity: 25

    nestif:
      min-complexity: 6

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

    dupl:
      threshold: 200

    nakedret:
      max-func-lines: 40

    errorlint:
      errorf: true
      asserts: true
      comparison: true

    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - interface

    exhaustive:
      default-signifies-exhaustive: true

    revive:
      rules:
        - name: exported
          disabled: false
        - name: package-comments
          disabled: false
        - name: var-naming
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: if-return
          disabled: false
        - name: superfluous-else
          disabled: false
        - name: unreachable-code
          disabled: false

    whitespace:
      multi-if: false
      multi-func: false

    misspell:
      locale: US

formatters:
  enable:
    - gofumpt # stricter gofmt
    - goimports # import formatting and sorting
    - gci # import grouping and organization

  settings:
    gci:
      sections:
        - standard # Standard library packages
        - default # External packages
        - prefix(github.com/jaeaeich/metis) # Your project packages
      custom-order: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
...
