x-healthcheck-http: &healthcheck-http
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 15s
  start_interval: 2s
services:
  postgres:
    image: postgres:18-alpine
    container_name: metis-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-metis}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      <<: *healthcheck-http
  metis-db-migrations:
    build:
      context: .
      dockerfile: deployment/images/migration.Dockerfile
    container_name: metis-db-migration
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      - "up"
  valkey:
    image: valkey/valkey:alpine3.22
    container_name: metis-valkey
    ports:
      - "6379:6379"
    command: valkey-server --requirepass ${REDIS_PASSWORD:-password}
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - valkey-cli -a ${REDIS_PASSWORD:-password} ping | grep PONG
      <<: *healthcheck-http
  nats:
    image: nats:2.12.4-alpine
    container_name: metis-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--http_port=8222"
      - "--user=${NATS_USER:-nats}"
      - "--pass=${NATS_PASSWORD:-nats}"
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--spider"
        - "-q"
        - "http://localhost:8222/healthz"
      <<: *healthcheck-http
  metis-api:
    build:
      context: .
      dockerfile: deployment/images/api.Dockerfile
    container_name: metis-api
    restart: on-failure
    depends_on:
      metis-db-migrations:
        condition: service_completed_successfully
      nats:
        condition: service_healthy
      valkey:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD:-password}@valkey:6379
      NATS_URL: nats://${NATS_USER:-nats}:${NATS_PASSWORD:-nats}@nats:4222
    ports:
      - "8080:8080"
  metis-engine-nextflow:
    build:
      context: .
      dockerfile: deployment/images/nextflow-engine.Dockerfile
    container_name: metis-engine-nextflow
    restart: on-failure
    depends_on:
      metis-db-migrations:
        condition: service_completed_successfully
      nats:
        condition: service_healthy
      valkey:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD:-password}@valkey:6379
      NATS_URL: nats://${NATS_USER:-nats}:${NATS_PASSWORD:-nats}@nats:4222
      KUBECONFIG: /root/.kube/config
    volumes:
      - ./deployment/configs/engine-config.yaml:/etc/metis/engine-config.yaml:ro
      - ./configs/scm:/root/.nextflow/scm:ro
      - ./workflows:/root/workflows:ro
      - ./configs/nextflow.config:/root/.nextflow/config:ro
      - ./configs/kubeconfig:/root/.kube/config:ro
    command: "metis-engine-generic server --engine-config /etc/metis/engine-config.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  metis-ui:
    build:
      context: .
      dockerfile: deployment/images/ui.Dockerfile
    container_name: metis-ui
    restart: on-failure
    depends_on:
      - metis-api
    environment:
      API_URL: http://metis-api:8080/
    ports:
      - "80:80"
