{{- if .Values.metis.plugins }}
{{- range $index, $plugin := .Values.metis.plugins }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metis.plugin.name" (dict "plugin" $plugin "global" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "metis.plugin.labels" (dict "plugin" $plugin "global" $) | nindent 4 }}
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $plugin.service.type | default "ClusterIP" }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ $plugin.service.port | default 50051 }}
      targetPort: grpc
  selector:
    {{- include "metis.plugin.selectorLabels" (dict "plugin" $plugin "global" $) | nindent 4 }}
{{- end }}
{{- end }}
