[[bin]]
name = "metis-api"
path = "src/main.rs"

[dependencies]
async-nats = { workspace = true }
async-stream = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
common = { path = "../common", version = "0.1.0" }
envy = { workspace = true }
futures = { workspace = true }
redis = { workspace = true }
serde = { features = [ "derive" ], workspace = true }
serde_json = { workspace = true }
sqlx = { features = [
  "chrono",
  "derive",
  "json",
  "macros",
  "postgres",
  "runtime-tokio-rustls",
  "uuid",
], workspace = true }
telemetry = { workspace = true }
thiserror = { workspace = true }
tokio = { features = [ "full" ], workspace = true }
tokio-stream = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
utoipa = { features = [ "axum_extras", "chrono", "uuid" ], workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { features = [ "serde", "v7" ], workspace = true }

[lints]
workspace = true

[package]
edition = "2024"
name = "metis-api"
version = "0.1.0"
