use async_trait::async_trait;
use common::models::{TaskLog, WorkflowFileInfo};

use crate::error::EngineError;

/// Public trait that engines must implement
/// The engine runtime is handled and manipulated by the engine config
/// but each engine has specific implementation and parsing logic after a run
/// has been finished or cancelled based on what backend it used, and that is
/// captured by this trait.
#[async_trait]
pub trait Engine: Send + Sync {
    /// Create a new instance of the engine
    fn new() -> Self
    where
        Self: Sized;
    /// Get workflow output files
    /// These are the files that are generated by the workflow,
    /// based on the backend used, they can be a different format or location.
    ///
    /// Example: For a local backend, the files might be stored in a specific
    /// directory.     ie file://path/to/result, for a cloud backend, the files might be stored in
    ///     a cloud storage service ie s3://bucket/path/to/result.
    ///     Files should be categorized (eg metadata, logs, results) based on
    /// engine specific     terminologies.
    #[allow(dead_code)]
    async fn get_workflow_results(
        &self,
    ) -> Result<
        Option<
            std::collections::HashMap<String, std::collections::HashMap<String, WorkflowFileInfo>>,
        >,
        EngineError,
    >;

    /// Get task execution logs
    /// These are the logs that are generated by the task,
    /// based on the backend used, they can be a different format or location.
    ///
    /// Example: For a local backend, the logs might be stored in a specific
    /// directory.     For a cloud backend, the logs might be stored in a
    /// cloud storage service.     Logs should be categorized (eg metadata,
    /// logs, results) based on engine specific     terminologies.
    async fn get_task_logs(&self) -> Result<Option<Vec<TaskLog>>, EngineError>;
}
